name: unit-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: | 
          go install gotest.tools/gotestsum@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          gotestsum --format testdox
